server {
    listen 80;
    server_tokens off;

    # Set the root directory where the static files are
    root /usr/share/nginx/html;
    index index.html;

    # Configuration for single-page application routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Handle assets/static files with long cache
    location /static/ {
        expires 1y;
        add_header Cache-Control "public";
    }

    # Default error page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}